version: "3.8"
services:
  demodb:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=demo
      - MONGO_INITDB_ROOT_PASSWORD=demo
      - MONGO_DB_USERNAME=demo
      - MONGO_DB_PASSWORD=demo
      - MONGO_DB=employee
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo:/home/mongodb
      - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
     
  demoserver:
    build: ./server
    ports:
      - "4080:4080"
      - "465:465"
      - "587:587"
      - "25:25"
    expose:
      - "4080"
      - "465"
      - "587"
      - "25"
    restart: always
    volumes:
      - ./uploads:/demoserver/images
    links:
      - demodb

  demoweb:
    build: ./client   
    restart: always 
    ports:
      - "4200:80" 
    links:
      - demoserver
    volumes: 
      - ./client-build:/usr/share/nginx/html
  nginx: 
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - demoserver
      - demoweb
